# Generated by Django 5.1.1 on 2024-10-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings_comments_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('FA', 'Fashion'), ('BAG', 'Bags'), ('TOY', 'Toys'), ('CAM', 'Cameras'), ('ELEC', 'Electronics'), ('HM', 'Home'), ('FD', 'Food/Drinks'), ('BK', 'Books'), ('STAT', 'Stationery'), ('SVC', 'Services'), ('NA', 'No Category Listed')], default='No Category Listed', max_length=50),
        ),
    ]
