# Generated by Django 5.1.1 on 2024-10-16 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_current_bid_alter_listing_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('NA', 'No Category Listed'), ('FA', 'Fashion'), ('BAG', 'Bags'), ('TOY', 'Toys'), ('CAM', 'Cameras'), ('ELEC', 'Electronics'), ('HM', 'Home'), ('FD', 'Food/Drinks'), ('BK', 'Books'), ('STAT', 'Stationery'), ('SVC', 'Services')], max_length=50),
        ),
    ]
