# Generated by Django 5.1.1 on 2024-10-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_current_bidder_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('NA', 'No Category Listed'), ('Fashion', 'Fashion'), ('Bags', 'Bags'), ('Toys', 'Toys'), ('Cameras', 'Cameras'), ('Electronics', 'Electronics'), ('Home', 'Home'), ('Food/Drinks', 'Food/Drinks'), ('Books', 'Books'), ('Stationery', 'Stationery'), ('Services', 'Services')], max_length=50),
        ),
    ]
